# Generated by Django 6.0.2 on 2026-02-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='name',
            new_name='priority_name',
        ),
    ]
